# generated by ./build-images-lock.sh on 2025-07-05 10:23:17
{  x86_64-linux = {
    "docker.io/openspeedtest/latest:latest" = "docker.io/openspeedtest/latest@sha256:16f9e946eda48660e4503c87e3d4f609b9cbdb23849544ac00aa88fa22f74023";
    "docker.io/clusterzx/paperless-ai:latest" = "docker.io/clusterzx/paperless-ai@sha256:ea2309b446ce478dd0bb0263de201229a218af7e217588f619ffaf34e3ebfbe3";
    "ghcr.io/ignisda/ryot:v8" = "ghcr.io/ignisda/ryot@sha256:b5d71b0789f96af14dfc1b3578234ce6888620917e87ef989f544ea26ea1093d";
    "ghcr.io/home-assistant/home-assistant:stable" = "ghcr.io/home-assistant/home-assistant@sha256:40c3e515a99de80775c3039f17a23f6c6e4365f63b9cb02445048ec11a5085e0";
  };
  aarch64-linux = {
    "docker.io/clusterzx/paperless-ai:latest" = "docker.io/clusterzx/paperless-ai@sha256:eacdcc356a5bf958bad39dcb8426fc8b50ea338239e01a2ace2330f430fb83c8";
    "ghcr.io/home-assistant/home-assistant:stable" = "ghcr.io/home-assistant/home-assistant@sha256:15f21b16a63247fe9d9199983798065679de3e8488bbf66f57689a6f694ae2fc";
    "docker.io/openspeedtest/latest:latest" = "docker.io/openspeedtest/latest@sha256:1912b4d18a8094e234ed6bf3b38bc3ebc485ee48bc270483da77db1c56f4e600";
    "ghcr.io/ignisda/ryot:v8" = "ghcr.io/ignisda/ryot@sha256:cb9ab613b97ecf3735742dcd02bf40b7f2ee1c3b62b731f02f6017a32126e69a";
  };
  armv7l-linux = {
  };
  armv6l-linux = {
  };
  i686-linux = {
    "docker.io/openspeedtest/latest:latest" = "docker.io/openspeedtest/latest@sha256:6ef09fe062bf9088c9781bd31b405d6103fee1b4e9293d7f5364ed20e4ed1eb2";
    "ghcr.io/home-assistant/home-assistant:stable" = "ghcr.io/home-assistant/home-assistant@sha256:7d80be19e3d1c2e39104b0c632bdf93d631e214cc20a417b8141bc304588fc65";
  };
}
